//Europe
INSERT INTO COUNTRIES VALUES ('BE', 'Belgium', 1);
INSERT INTO COUNTRIES VALUES ('CH', 'Switzerland', 1);
INSERT INTO COUNTRIES VALUES ('DE', 'Germany', 1);
INSERT INTO COUNTRIES VALUES ('DK', 'Denmark', 1);
INSERT INTO COUNTRIES VALUES ('FR', 'France', 1);
INSERT INTO COUNTRIES VALUES ('IT', 'Italy', 1);
INSERT INTO COUNTRIES VALUES ('NL', 'Netherlands', 1);
INSERT INTO COUNTRIES VALUES ('UK', 'United Kingdom', 1);

//Americas
INSERT INTO COUNTRIES VALUES ('AR', 'Argentina', 2);
INSERT INTO COUNTRIES VALUES ('BR', 'Brazil', 2);
INSERT INTO COUNTRIES VALUES ('CA', 'Canada', 2);
INSERT INTO COUNTRIES VALUES ('MX', 'Mexico', 2);
INSERT INTO COUNTRIES VALUES ('US', 'United States of America', 2);

//Asia
INSERT INTO COUNTRIES VALUES ('AU', 'Australia', 3);
INSERT INTO COUNTRIES VALUES ('CN', 'China', 3);
INSERT INTO COUNTRIES VALUES ('IN', 'India', 3);
INSERT INTO COUNTRIES VALUES ('JP', 'Japan', 3);
INSERT INTO COUNTRIES VALUES ('ML', 'Malaysia', 3);
INSERT INTO COUNTRIES VALUES ('SG', 'Singapore', 3);

//Middle East and Africa
INSERT INTO COUNTRIES VALUES ('EG', 'Egypt', 4);
INSERT INTO COUNTRIES VALUES ('IL', 'Israel', 4);
INSERT INTO COUNTRIES VALUES ('KW', 'Kuwait', 4);
INSERT INTO COUNTRIES VALUES ('NG', 'Nigeria', 4);
INSERT INTO COUNTRIES VALUES ('ZM', 'Zambia', 4);
INSERT INTO COUNTRIES VALUES ('ZW', 'Zimbabwe', 4);
